### PR TITLE
Space Race Minigame

### PR DESCRIPTION
**Pull request by Cooldude2606**
- Added Space Race minigame
- Added Minigame Surface module as a modified version of Redmew Surface
- Added some map gen utils from redmew code base
- Added redmew locale files for common and retailer

A few liberties I took while making it:
- While the map is generating you remain in the lobby rather than being frozen on the surface
- I edited redmew map gen to check that a surface is valid to avoid errors with /stop
- I removed the snake lobby game because that was a lot of extra modules that would be needed
- No other redmew modules were ported over as that would be extra work, these means there is no delay on turrets

### CODE REVIEW

**Comment by Cooldude2606** [comment]
The players should know which team they are on. I purposely removed the balance checks so that a team of three players is able to take on a team of five if they so wish. But what do you mean by "make the teams decide".

**Comment by tovernaar123** [comment]
what i mean i make the teams decided that i just pick 50% for 1 team and 50% for the other but as you said the players shood know what team (mabye make the gui labels a option so we can have custum named teams)

**Comment by Cooldude2606** [comment]
Still to understand what you are saying about "make the teams decide"; do you mean have the mini game decide which players are on which team automatically? It is possible to have it done via command if you want to do that but without external input there is no way to know which players should be on each team. As for having the labels be different, it would be possible but will lead to inconsistencies as other guis outside the module may rely on the force names which can not be changed.

**Comment by tovernaar123** [comment]
yeah i ment games decides what players go in what team but as you said that a bad idea but with the labels i do think even with the inconsistencies it would be better (as you would just have t o click on youre own team name) mabye make it like team name (force name)

**Comment by Cooldude2606** [comment]
I will make it possible to change the team names with args to the start command as they would be no other way to get the infomation. And again I cant change the force names as two many internals rely on them.

**Comment by tovernaar123** [comment]
also be sure to add i to the start gui

**Comment by Cooldude2606** [comment]
Actully from second reading it appears that the force name does not matter as the force is stored as a primitive in global.

**Comment by tovernaar123** [comment]
well i gues then make the whole thing custum

**Pull request merged**
